### ISSUE TITLE
另一个程序正在使用此文件，进程无法访问

### ISSUE THREAD

**Issue by QTJ-Respository** [2noise/ChatTTS#388]
WARNING:ChatTTS.utils.download:please add parameter --update to download the latest assets.
Traceback (most recent call last):
  File "D:\test_project\ChatTTS-online\ChatTTS\examples\web\webui.py", line 157, in <module>
    main()
  File "D:\test_project\ChatTTS-online\ChatTTS\examples\web\webui.py", line 148, in main
    chat.load_models()
  File "D:\test_project\ChatTTS-online\ChatTTS\ChatTTS\core.py", line 60, in load_models
    if not check_all_assets(update=True):
  File "D:\test_project\ChatTTS-online\ChatTTS\ChatTTS\utils\download.py", line 62, in check_all_assets
    if not check_model(
  File "D:\test_project\ChatTTS-online\ChatTTS\ChatTTS\utils\download.py", line 38, in check_model
    os.rename(str(target), bakfile)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'D:\\test_project\\ChatTTS-online\\ChatTTS\\asset\\GPT.pt' -> 'D:\\test_project\\ChatTTS-online\\ChatTTS\\asset\\GPT.pt.bak'
INFO:httpx:HTTP Request: GET https://checkip.amazonaws.com/ "HTTP/1.1 200 "
INFO:httpx:HTTP Request: GET https://api.gradio.app/pkg-version "HTTP/1.1 200 OK"

**Comment by fumiama** [comment]
应该是同时启动了多个实例，去任务管理器看看，将python相关全关掉即可，嫌麻烦也可以直接重启电脑。

**Comment by Bobo-1125** [comment]
我这边遇到的情况是GPT.pt文件下载的不完整，重新下载替换一下就好了

**Comment by zong4** [comment]
把asset文件夹删了重新下就行

**Comment by jwawawawwa** [comment]
不胜感激

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jwawawawwa** [comment]
当我删除 visual studio 的时候，再运行发现OSError: [WinError 126] 找不到指定的模块，是缺少了 fbgemm.dll 。我必须有 visual studio 才能有 fbgemm.dll 吗？
________________________________
发件人: HuYihan ***@***.***>
发送时间: 2024年8月14日 12:38
收件人: 2noise/ChatTTS ***@***.***>
抄送: jwawawawwa ***@***.***>; Comment ***@***.***>
主题: Re: [2noise/ChatTTS] 另一个程序正在使用此文件，进程无法访问 (Issue #388)


把asset文件夹删了重新下就行

―

**Comment by jwawawawwa** [comment]
下载完成就好了，现在又有新问题了……
[ERROR] #1.3 download file asset/Decoder.pt err: read tcp 192.168.1.101:58914->13.32.99.87:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
[ERROR] #1.4 download file asset/GPT.pt err: read tcp 192.168.1.101:58913->13.32.99.87:443: wsarecv: A connection attempt failed because the connected party did not properly respond
after a period of time, or established connection failed because connected host has failed to respond.
[INFO] all download tasks finished.
vocos not initialized.
tokenizer not initialized.
decoder not initialized.
需要重新下载吗
________________________________
发件人: 夏 一本 ***@***.***>
发送时间: 2024年8月14日 14:29
收件人: 2noise/ChatTTS ***@***.***>
主题: 回复: [2noise/ChatTTS] 另一个程序正在使用此文件，进程无法访问 (Issue #388)

当我删除 visual studio 的时候，再运行发现OSError: [WinError 126] 找不到指定的模块，是缺少了 fbgemm.dll 。我必须有 visual studio 才能有 fbgemm.dll 吗？
________________________________
发件人: HuYihan ***@***.***>
发送时间: 2024年8月14日 12:38
收件人: 2noise/ChatTTS ***@***.***>
抄送: jwawawawwa ***@***.***>; Comment ***@***.***>
主题: Re: [2noise/ChatTTS] 另一个程序正在使用此文件，进程无法访问 (Issue #388)


把asset文件夹删了重新下就行

―
